version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: sme-postgres
    environment:
      POSTGRES_DB: smedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sme_pgdata:/var/lib/postgresql/data

volumes:
  sme_pgdata:
